// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4rnTBlbLPL5shsQ7T5D2x6V2IWaIth8I',
    appId: '1:599729454122:web:9bdc8143361e9b7d541753',
    messagingSenderId: '599729454122',
    projectId: 'reddit-clone-5411f',
    authDomain: 'reddit-clone-5411f.firebaseapp.com',
    storageBucket: 'reddit-clone-5411f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkzkM6j2Yb8omF_ueNuM2kMyhm48fuz44',
    appId: '1:599729454122:android:877bb85e61cd59fe541753',
    messagingSenderId: '599729454122',
    projectId: 'reddit-clone-5411f',
    storageBucket: 'reddit-clone-5411f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU3iaykgqrYCNxyRDsNXZJRmlOFHYDehc',
    appId: '1:599729454122:ios:b2fe9f12e15ed876541753',
    messagingSenderId: '599729454122',
    projectId: 'reddit-clone-5411f',
    storageBucket: 'reddit-clone-5411f.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );
}
